# Generated by Django 4.2.7 on 2024-01-26 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Documents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_text", models.TextField()),
                ("output_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("words_used", models.PositiveIntegerField(default=0)),
                ("purpose", models.CharField(blank=True, max_length=100, null=True)),
                ("level", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "readibility",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("document_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
