# Generated by Django 4.2.7 on 2023-12-18 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MetaTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_identifier", models.CharField(max_length=100)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("keywords", models.CharField(blank=True, max_length=500)),
                ("og_title", models.CharField(blank=True, max_length=200)),
                ("og_description", models.TextField(blank=True)),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="og_images/"),
                ),
                ("twitter_title", models.CharField(blank=True, max_length=200)),
                ("twitter_description", models.TextField(blank=True)),
                (
                    "twitter_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="twitter_images/"
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="translations.language",
                    ),
                ),
            ],
        ),
    ]
