# Generated by Django 4.2.7 on 2024-01-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metatag",
            name="page_identifier",
            field=models.CharField(
                choices=[
                    ("main", "Main"),
                    ("pricing", "Pricing"),
                    ("sign_up", "Sign Up"),
                    ("sign_in", "Sign In"),
                    ("log_out", "Log Out"),
                    ("confirm_page", "Confirm Page"),
                    ("forgot_password", "Forgot Password"),
                ],
                max_length=100,
            ),
        ),
    ]
