name: Python CI/CD

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        env: 
          SSH_HOST: ${{secrets.SSH_HOST}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_USER: ${{secrets.SSH_USER}}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
          chmod 600 ~/.ssh/github
          cat >>~/.ssh/config <<END
          Host target
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/github
            LogLevel ERROR
            StrictHostKeyChecking no
          END

      - name: Run down
        run: |
          ssh target "cd /var/www/summy_saas &&  sudo git pull && source venv/bin/activate && pip install -r reqs.txt "
      - name: Run Build
        run: |
          ssh target "cd /var/www/summy_saas && sudo systemctl restart gunicorn"


